title: Belmont Police Blotter Feed

markdown: kramdown

github_username: kenyonj

plugins:
  - jekyll-feed

collections:
  incidents:
    output: true
    permalink: /:collection/:path/

exclude:
  - .git
  - .github
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - db/
  - lib/
  - node_modules
  - rakefile.rb
  - spec/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
