title: Belmont Police Blotter Feed
description: Feed for Belmont Police Incident Reports

markdown: kramdown

github_username: kenyonj
repository: kenyonj/belmont-police-blotter

plugins:
  - jekyll-feed
  - jekyll-default-layout

collections:
  incidents:
    output: true
    permalink: /:collection/:path/

exclude:
  - .git
  - .github
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - db/
  - lib/
  - node_modules
  - rakefile.rb
  - spec/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: "_incidents"
    values:
      layout: "default"
