name: Check for changes

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 * * * *" # Every hour

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data
        run: curl "https://www.belmontpd.org/resident-resources/pages/police-blotter" -o data.json

      - name: Fetch Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: data.json
          key: ${{ hashFiles('data.json') }}

      - name: Page has changed
        run: exit 0
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Page has not changed
        run: exit 1
        if: steps.cache.outputs.cache-hit == 'true'
